version: '3'
services:
  apaxy:
    image: apaxy
    build:
      context: .
      args:
        apaxyPath: ''
    labels:
      - traefik.enable=true
      - traefik.http.routers.insta_frontend.rule=Host(`files.derunix.ru`)
      - traefik.http.routers.insta_frontend.entrypoints=websecure
      - traefik.http.routers.insta_frontend.tls.certresolver=myresolver
      - traefik.http.services.insta_frontend.loadbalancer.server.port=8080
    expose:
      - 8080
    volumes:
      - /storage/:/usr/local/apache2/htdocs/share/
